application:
  message: Azure Test
 
message: Config from application.yml on Github
logging:
  level:
    io:
      spring: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
