application:
  message: Azure Test
 
message: Config from application.yml - Azure Service Bus Spring Cloud

logging: # <----New sections below
  level:
    io:
      spring: DEBUG
      
#feature:
#  toggle: false
